### ISSUE TITLE
Bump the package version

### ISSUE THREAD

**Issue by lott-ai** [jacobmarshall/webpack-bugsnag-plugin#3]
please :)

**Comment by jmshal** [comment]
Sorry Chris, it's been pretty non-stop recently. But I WILL will will push a new version tonight (NZST). If I don't, you have permission to send your fist in a box to my address, so you can punch me square in the face. I'll bump the version along with the upcoming changes to https://github.com/jmshal/bugsnag-sourcemaps as well. My apologies for the delay!

**Comment by lott-ai** [comment]
Haha no worries, just thought I'd give you a nudge. Thanks!

**Comment by jmshal** [comment]
We can all sleep now, 31c28a7fadd6a800bbcab1ea8b5e6a97f4186949 :)
