### ISSUE TITLE
API key validation error not specific enough

### ISSUE THREAD

**Issue by sgtpepper43** [jacobmarshall/webpack-bugsnag-plugin#5]
The error you get when you put in an _invalid_ api key is
> You must provide your Bugsnag API key to the BugsnagPlugin.

But I _did_ provide an api key, it was just a fake one that wasn't long enough. It should be more clear and specify that it failed validation, not that it's missing.

**Comment by jmshal** [comment]
Thanks @sgtpepper43, I actually had planned on removing the length validation on the API key, following a discussion with one of the peeps at Bugsnag - because there is no guarantee the key will always be MD5-like (32 characters long).

b017ae992d5fedb07d6977df0f93d60d50949f38
