### ISSUE TITLE
`git remote get-url origin` fails with Git <2.7

### ISSUE THREAD

**Issue by nicooprat** [jacobmarshall/webpack-bugsnag-plugin#8]
This command isn't available with git <2.7: https://stackoverflow.com/questions/4089430/how-can-i-determine-the-url-that-a-local-git-repository-was-originally-cloned-fr

Failed on my machine, updated Git, works great. But I'm using Netlify and it looks like their build system is also using an older Git version. I'll let them know but I guess they won't be able to update it soon. Could you use a more compatible command like `git config --get remote.origin.url`? 

Thanks.

**Comment by jmshal** [comment]
Thanks for letting me know, I'll sort out a fix within the next hour! 😊

**Comment by jmshal** [comment]
I've just published ~v0.1.2~ v0.1.3 now. If you update, all should be working :)

Thank you for your patience!

Edit: v0.1.2 was published with Node 6, instead of Node 8 (my fault, sorry). I have published v0.1.3 which has been built correctly.

**Comment by nicooprat** [comment]
That was quick, thanks!
